# Default values for napcat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 3

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: mlikiowa/napcat-docker
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  type: ClusterIP
  annotations: 
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "napcat-webui-id"

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: "traefik"
  webui:
    hosts:
      - host: webui.example.com
  hosts: []
    # - host: api.example.com
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
    #       port: 3000
  tls: []
  #  - secretName: webui.example.com-tls
  #    hosts:
  #      - webui.example.com
  #      - api.example.com

httpServers:
  - name: httpServer
    enabled: true
    host: 0.0.0.0
    port: 3000
    enableCors: false
    enableWebsocket: false
    messagePostFormat: "array"
    token: "WhatIsLove_BabyDontHurtMe"
    debug: false

httpClients: []
  # - name: httpClient
  #   enabled: false
  #   url: http://localhost:8080
  #   messagePostFormat: array
  #   reportSelfMessage: false
  #   token: 'WhatIsLove_BabyDontHurtMe'
  #   debug: false

websocketServers: []
  # - name: WsServer
  #   enabled: false
  #   host: 0.0.0.0
  #   port: 3001
  #   messagePostFormat: array
  #   reportSelfMessage: false
  #   token: ''
  #   enableForcePushEvent: true
  #   debug: false
  #   heartInterval: 30000

websocketClients: []
  # - name: WsClient
  #   enabled: false
  #   url: ws://localhost:8082
  #   messagePostFormat: array
  #   reportSelfMessage: false
  #   reconnectInterval: 5000
  #   token: ''
  #   debug: false
  #   heartInterval: 30000

musicSignUrl:
enableLocalFile2Url: false
parseMultMsg: false

fileLog: false
consoleLog: true
fileLogLevel: debug
consoleLogLevel: info
packetServer: ''
